jobs:
  - job: DockerPush
    displayName: Push
    dependsOn: BuildAndScan
    steps:
      - task: Docker@2
        displayName: Docker - Login
        inputs:
          command: login
          containerRegistry: $(registryConnection)

      - bash: |
          docker build -t $(dockerImage):$(imageTag) .
          docker push $(dockerImage):$(imageTag)
        displayName: Docker - Build and Push

      - task: Docker@2
        displayName: Docker - Logout
        inputs:
          command: logout
          containerRegistry: $(registryConnection)